apiVersion: v1
entries:
  access-manager:
  - apiVersion: v1
    appVersion: 0.5.1
    created: "2021-01-25T17:00:56.467226305Z"
    description: Kubernetes-Operator to simplify RBAC configurations
    digest: f085b2c29e784a803f011a9848e7e96b5dad7860f5e23d5174baf745b984807c
    home: https://github.com/ckotzbauer/access-manager
    keywords:
    - kubernetes-operator
    - operator
    - rbac
    - secret
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: access-manager
    sources:
    - https://github.com/ckotzbauer/access-manager
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/access-manager-0.5.1/access-manager-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v1
    appVersion: 0.5.0
    created: "2021-01-10T15:56:58.786360935Z"
    description: Kubernetes-Operator to simplify RBAC configurations
    digest: 1c66823398720b1b68e2c4e78a2d56eac059b46e6362a86f3f1bda7323d95a42
    home: https://github.com/ckotzbauer/access-manager
    keywords:
    - kubernetes-operator
    - operator
    - rbac
    - secret
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: access-manager
    sources:
    - https://github.com/ckotzbauer/access-manager
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/access-manager-0.5.0/access-manager-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v1
    appVersion: 0.4.1
    created: "2020-11-01T18:37:08.379543072Z"
    description: Kubernetes-Operator to simplify RBAC configurations
    digest: b8755c54005134713ee8d42a90300df92a8dc8ee8e7feca9a52b4ec72cf4ca40
    home: https://github.com/ckotzbauer/access-manager
    keywords:
    - kubernetes-operator
    - operator
    - rbac
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: access-manager
    sources:
    - https://github.com/ckotzbauer/access-manager
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/access-manager-0.4.1/access-manager-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v1
    appVersion: 0.4.0
    created: "2020-09-22T17:51:01.955078948Z"
    description: Kubernetes-Operator to simplify RBAC configurations
    digest: 15ab4d68703471ed281af6fe1aa76aad47d41fbe14100eb4653cd5252434d38d
    home: https://github.com/ckotzbauer/access-manager
    keywords:
    - kubernetes-operator
    - operator
    - rbac
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: access-manager
    sources:
    - https://github.com/ckotzbauer/access-manager
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/access-manager-0.4.0/access-manager-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    appVersion: 0.3.0
    created: "2020-08-30T15:21:06.474342635Z"
    description: Kubernetes-Operator to simplify RBAC configurations
    digest: 0b77b459783debf4d457dc0d15ff4bfdbfa42ddd1566ac6bf86709c5c4fb576d
    home: https://github.com/ckotzbauer/access-manager
    keywords:
    - kubernetes-operator
    - operator
    - rbac
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: access-manager
    sources:
    - https://github.com/ckotzbauer/access-manager
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/access-manager-0.3.0/access-manager-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: 0.2.0
    created: "2020-07-18T10:36:24.677132496Z"
    description: Kubernetes-Operator to simplify RBAC configurations
    digest: 804ab6169962ec1f5a4c523cfe1a36f43d79532fe84e43b2ae78598e0c5f4861
    home: https://github.com/ckotzbauer/access-manager
    keywords:
    - kubernetes-operator
    - operator
    - rbac
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: access-manager
    sources:
    - https://github.com/ckotzbauer/access-manager
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/access-manager-0.2.0/access-manager-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-06-11T11:12:20.524614604Z"
    description: Kubernetes-Operator to simplify RBAC configurations
    digest: 41a145c680c8436996d0abfa26bab201004a3fc2c7afe3b1bdf6eee2c7395b74
    home: https://github.com/ckotzbauer/access-manager
    keywords:
    - kubernetes-operator
    - operator
    - rbac
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: access-manager
    sources:
    - https://github.com/ckotzbauer/access-manager
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/access-manager-0.1.0/access-manager-0.1.0.tgz
    version: 0.1.0
  cadvisor:
  - apiVersion: v1
    appVersion: 0.38.6
    created: "2021-01-10T15:59:37.559728962Z"
    description: A chart for a Cadvisor deployment
    digest: 4bf1b9e87d579fb89797b2137275dab1459576d7e8dbdef7df9317730a6c702b
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.2.2/cadvisor-1.2.2.tgz
    version: 1.2.2
  - apiVersion: v1
    appVersion: 0.38.4
    created: "2020-11-15T20:40:11.56535955Z"
    description: A chart for a Cadvisor deployment
    digest: f3bfc35f3c956d68b9621b802b67cdde10756c35bfe0fa182befd201279523d5
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.2.1/cadvisor-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v1
    appVersion: 0.37.0
    created: "2020-09-16T15:32:33.562965484Z"
    description: A chart for a Cadvisor deployment
    digest: 67698f5c48a4a200b97900e03c040ef7a53fd0dbe6c8d5adc3706f6be6015b14
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.2.0/cadvisor-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v1
    appVersion: 0.36.0
    created: "2020-09-16T10:16:19.780833964Z"
    description: A chart for a Cadvisor deployment
    digest: e0fbf7baac086c9a4edd5dabe6bb84b92ebe6c70163ff14192698277f178548a
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.1.4/cadvisor-1.1.4.tgz
    version: 1.1.4
  - apiVersion: v1
    appVersion: 0.36.0
    created: "2020-08-06T06:44:04.504980403Z"
    description: A chart for a Cadvisor deployment
    digest: a18644092e0049910a8dba1b85c779c74df0ae4ea05605af245988d2a5308b0f
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.1.3/cadvisor-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v1
    appVersion: 0.36.0
    created: "2020-07-18T09:14:16.332817896Z"
    description: A chart for a Cadvisor deployment
    digest: d90933ba8d96db2d324843bfa3be2f7d7ef7d98fda8029e06bfd3909daf02823
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.1.2/cadvisor-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v1
    appVersion: 0.36.0
    created: "2020-05-15T07:32:30.785504804Z"
    description: A chart for a Cadvisor deployment
    digest: c2dcc08815406f00ca8168b01d460f2efdd068af56b35dc3bd4807160c7f7ae2
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.1.1/cadvisor-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v1
    appVersion: 0.36.0
    created: "2020-03-14T09:05:27.691263834Z"
    description: A chart for a Cadvisor deployment
    digest: 5f75dd4d7d4e3d0517a2ac6b64f5303901d90fda650fe58283d43c6c29f7b8d1
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.1.0/cadvisor-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    appVersion: 0.36.0
    created: "2020-03-08T15:40:42.149854342Z"
    description: A chart for a Cadvisor deployment
    digest: b0676dfa42431c73061ac5550a73349c7b0a27c7d52ae9b013ce986d4466f2f8
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.0.1/cadvisor-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: 0.35.0
    created: "2020-01-25T08:17:05.975971472Z"
    description: A chart for a Cadvisor deployment
    digest: f6494fbdbcd5a0e9d3468ef9c483edc808bce245dbd2f311eaef1190868ffca9
    home: https://github.com/google/cadvisor
    keywords:
    - prometheus
    - cadvisor
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: cadvisor
    sources:
    - https://github.com/google/cadvisor
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/cadvisor-1.0.0/cadvisor-1.0.0.tgz
    version: 1.0.0
  nfs-client-provisioner:
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2020-11-15T20:41:41.9241624Z"
    description: nfs-client is an automatic provisioner that used your *already configured* NFS server, automatically creating Persistent Volumes.
    digest: 65438d777eaccd0e895da53c2fb842b791dce6d245c69a1f4d50a05945066176
    home: https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
    keywords:
    - nfs
    - storage
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: nfs-client-provisioner
    sources:
    - https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/nfs-client-provisioner-1.0.2/nfs-client-provisioner-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2020-05-15T07:32:30.894432252Z"
    description: nfs-client is an automatic provisioner that used your *already configured* NFS server, automatically creating Persistent Volumes.
    digest: 8509d227702f606b012af6fca182abbe3a8cbb6f5994b473e3ff23e0bfde62ce
    home: https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
    keywords:
    - nfs
    - storage
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: nfs-client-provisioner
    sources:
    - https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/nfs-client-provisioner-1.0.1/nfs-client-provisioner-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2020-04-13T15:39:47.395534606Z"
    description: nfs-client is an automatic provisioner that used your *already configured* NFS server, automatically creating Persistent Volumes.
    digest: 63ed3b319d3f810efec0e016baf9e4a98d7e04be19c01a13c240c15ccb30b4dc
    home: https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
    keywords:
    - nfs
    - storage
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: nfs-client-provisioner
    sources:
    - https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/nfs-client-provisioner-1.0.0/nfs-client-provisioner-1.0.0.tgz
    version: 1.0.0
  prometheus-blackbox-exporter:
  - apiVersion: v1
    appVersion: 0.18.0
    created: "2020-11-01T18:44:47.455627758Z"
    description: Prometheus Blackbox Exporter
    digest: b371ef8e218514e6db5373ad29172a5e4781d985de463924ce444190da61e05f
    home: https://github.com/prometheus/blackbox_exporter
    keywords:
    - prometheus
    - blackbox
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: prometheus-blackbox-exporter
    sources:
    - https://github.com/prometheus/blackbox_exporter
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/prometheus-blackbox-exporter-1.0.3/prometheus-blackbox-exporter-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    appVersion: 0.17.0
    created: "2020-06-29T17:18:12.801512408Z"
    description: Prometheus Blackbox Exporter
    digest: 068f55691d7cce5a356d6dba42cdde57553632580402077e81ea6d9a5d60b06b
    home: https://github.com/prometheus/blackbox_exporter
    keywords:
    - prometheus
    - blackbox
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: prometheus-blackbox-exporter
    sources:
    - https://github.com/prometheus/blackbox_exporter
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/prometheus-blackbox-exporter-1.0.2/prometheus-blackbox-exporter-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: 0.16.0
    created: "2020-05-15T07:32:31.017513998Z"
    description: Prometheus Blackbox Exporter
    digest: 36fb959245ab8c5fff86ad0a9f4937d5f4cf60b7b6274af950fef391937fc138
    home: https://github.com/prometheus/blackbox_exporter
    keywords:
    - prometheus
    - blackbox
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: prometheus-blackbox-exporter
    sources:
    - https://github.com/prometheus/blackbox_exporter
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/prometheus-blackbox-exporter-1.0.1/prometheus-blackbox-exporter-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: 0.16.0
    created: "2020-01-25T08:22:52.781973581Z"
    description: Prometheus Blackbox Exporter
    digest: ee30a24329fe71d3755574b924a0a577f24279da87d0d37b174905b74ecb77d8
    home: https://github.com/prometheus/blackbox_exporter
    keywords:
    - prometheus
    - blackbox
    - monitoring
    maintainers:
    - email: christian.kotzbauer@gmail.com
      name: ckotzbauer
    name: prometheus-blackbox-exporter
    sources:
    - https://github.com/prometheus/blackbox_exporter
    - https://github.com/ckotzbauer/helm-charts
    urls:
    - https://github.com/ckotzbauer/helm-charts/releases/download/prometheus-blackbox-exporter-1.0.0/prometheus-blackbox-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2020-01-25T08:17:05.703619461Z"
